### ISSUE TITLE
~5 seconds lag while opening first new tab on Chrome

### ISSUE THREAD

**Issue by adiker** [OllieTerrance/Homely#6] opened 2017-01-31 11:07 UTC
Hi, after the latest Chrome update I started to receive really slow response from Homely — only if the new tab with it was not already opened. In other words, if any other new tab with Homely is already opened, it works just fine. Otherwise, I have to wait around 3-10 seconds. Other extensions do not seem to affect it.

Cheers!

**Comment by OllieTerrance** [comment] 2017-01-31 20:16
What Chrome channel are you on?  I'm using 57.0.2987.19 dev here -- both first and additional new tabs seem to take ~1.5 seconds for me.  Not sure if this was any faster in Chrome 56.

Does Homely speed up if you disable all the notification providers in settings?  (Each one is essentially another site to load, though it shouldn't block the rest of the page loading...)

**Comment by adiker** [comment] 2017-02-01 08:45
Hey, thanks for the rapid reply!

I use Chrome on macOS, its version is 56.0.2924.76 (64-bit).
Disabled all the notifications (both in Homely and Chrome) and also all extensions, yet nothing changed really...

**Comment by OllieTerrance** [comment] 2017-02-01 20:50
Ok, so I've tried on a couple of machines, Chrome 56 and 57, can't reproduce the slowness here.  😞

Does this affect any other new tab pages, or just Homely?  If you use an existing tab and navigate to `chrome://newtab`, is it still slow to load?  If you install Homely in a new Chrome profile, is it still slow?

**Comment by adiker** [comment] 2017-02-04 15:27
Hi again!

Tried all the ways you outlined, it is still slow, unfortunately. Further, installed Homely on Chromium (58.0.3003.0 (64-bit)) also on macOS and the effect is the same...

On the other hand, I already made a habit of keeping one empty tab pinned in the corner, so it is not a great deal after all. :)

**Comment by OllieTerrance** [comment] 2017-02-08 09:01
Not sure what to recommend here.  🤔

Both machines here are Windows, so maybe it's something introduced to Chrome for Mac recently?  Would be good to know if anyone else can reproduce this, so far I'm at a bit of a dead end...

**Comment by adiker** [comment] 2017-02-08 09:57
Ok, let's see! Do you know if I should delete this issue now or it is ok if it stays here?

In any event, many thanks for the extension. Proved to be hugely helpful in different ways.

**Comment by OllieTerrance** [comment] 2017-02-12 10:04
I'm inclined to close it, for now at least, as this feels like more of a Chrome issue.  Can always reopen if more people can reproduce it, or if a solution comes to light from other similar extensions.  Currently I'm unsure what can/should be fixed here.

**Closed by OllieTerrance** 2017-02-12 10:04 UTC
